# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'samurai.ui'
#
# Created: Thu Apr 26 17:13:55 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1006, 709)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "اكادمية الساموراي للفنون القتالية", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 40, 971, 621))
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_27 = QtGui.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(6, 120, 951, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Umpush"))
        font.setPointSize(48)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("color: rgb(255, 0, 4);"))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "أكادمية ألساموراي للفنون ألقتالية ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(200, 310, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "أدارة أللاعبين", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(0, 530, 961, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "تصميم : مصطفي محمود فتحي www.cmpsamurai.com  - digital_ninja01@hotmail.com  2012 ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(190, 230, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet(_fromUtf8("color: rgb(0, 85, 0);"))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "ك. عيد محمد", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 10, 941, 571))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_12 = QtGui.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(770, 30, 141, 20))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "عرض اللاعبين في لعبة :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(830, 70, 81, 20))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "اسم اللاعب:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.txt_search_name = QtGui.QLineEdit(self.tab_4)
        self.txt_search_name.setGeometry(QtCore.QRect(580, 70, 241, 27))
        self.txt_search_name.setObjectName(_fromUtf8("txt_search_name"))
        self.bt_search = QtGui.QPushButton(self.tab_4)
        self.bt_search.setGeometry(QtCore.QRect(580, 110, 97, 27))
        self.bt_search.setText(QtGui.QApplication.translate("MainWindow", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_search.setObjectName(_fromUtf8("bt_search"))
        self.combo_search_viewbygame = QtGui.QComboBox(self.tab_4)
        self.combo_search_viewbygame.setGeometry(QtCore.QRect(580, 30, 171, 27))
        self.combo_search_viewbygame.setObjectName(_fromUtf8("combo_search_viewbygame"))
        self.combo_search_viewbygame.addItem(_fromUtf8(""))
        self.combo_search_viewbygame.setItemText(0, QtGui.QApplication.translate("MainWindow", "Aikido", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_search_viewbygame.addItem(_fromUtf8(""))
        self.combo_search_viewbygame.setItemText(1, QtGui.QApplication.translate("MainWindow", "KungFu", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_search_viewbygame.addItem(_fromUtf8(""))
        self.combo_search_viewbygame.setItemText(2, QtGui.QApplication.translate("MainWindow", "Free Style", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_search_viewbygame.addItem(_fromUtf8(""))
        self.combo_search_viewbygame.setItemText(3, QtGui.QApplication.translate("MainWindow", "Golden", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_edit = QtGui.QGroupBox(self.tab_4)
        self.gb_edit.setEnabled(False)
        self.gb_edit.setGeometry(QtCore.QRect(20, 10, 411, 541))
        self.gb_edit.setTitle(QtGui.QApplication.translate("MainWindow", "معلومات اللاعب ", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_edit.setObjectName(_fromUtf8("gb_edit"))
        self.label_5 = QtGui.QLabel(self.gb_edit)
        self.label_5.setGeometry(QtCore.QRect(330, 70, 67, 17))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "الاسم :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.gb_edit)
        self.label_6.setGeometry(QtCore.QRect(320, 110, 81, 20))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "تاريخ الميلاد :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_20 = QtGui.QLabel(self.gb_edit)
        self.label_20.setGeometry(QtCore.QRect(320, 150, 81, 20))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "النشاط :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.gb_edit)
        self.label_21.setGeometry(QtCore.QRect(300, 420, 101, 20))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "تاريخ الانضمام  :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.txt_edit_name = QtGui.QLineEdit(self.gb_edit)
        self.txt_edit_name.setGeometry(QtCore.QRect(20, 70, 271, 27))
        self.txt_edit_name.setObjectName(_fromUtf8("txt_edit_name"))
        self.date_edit_bd = QtGui.QDateEdit(self.gb_edit)
        self.date_edit_bd.setGeometry(QtCore.QRect(20, 110, 271, 27))
        self.date_edit_bd.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "M/d/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_edit_bd.setObjectName(_fromUtf8("date_edit_bd"))
        self.combo_edit_game = QtGui.QComboBox(self.gb_edit)
        self.combo_edit_game.setGeometry(QtCore.QRect(20, 150, 271, 27))
        self.combo_edit_game.setObjectName(_fromUtf8("combo_edit_game"))
        self.combo_edit_game.addItem(_fromUtf8(""))
        self.combo_edit_game.setItemText(0, QtGui.QApplication.translate("MainWindow", "Aikido", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_edit_game.addItem(_fromUtf8(""))
        self.combo_edit_game.setItemText(1, QtGui.QApplication.translate("MainWindow", "KungFu", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_edit_game.addItem(_fromUtf8(""))
        self.combo_edit_game.setItemText(2, QtGui.QApplication.translate("MainWindow", "Free Style", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_edit_game.addItem(_fromUtf8(""))
        self.combo_edit_game.setItemText(3, QtGui.QApplication.translate("MainWindow", "Golden", None, QtGui.QApplication.UnicodeUTF8))
        self.date_edit_joindate = QtGui.QDateEdit(self.gb_edit)
        self.date_edit_joindate.setGeometry(QtCore.QRect(20, 420, 271, 27))
        self.date_edit_joindate.setDate(QtCore.QDate(2012, 1, 1))
        self.date_edit_joindate.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "M/d/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_edit_joindate.setObjectName(_fromUtf8("date_edit_joindate"))
        self.bt_edit_saveedit = QtGui.QPushButton(self.gb_edit)
        self.bt_edit_saveedit.setGeometry(QtCore.QRect(190, 490, 97, 27))
        self.bt_edit_saveedit.setText(QtGui.QApplication.translate("MainWindow", "حفظ التعديل", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_edit_saveedit.setObjectName(_fromUtf8("bt_edit_saveedit"))
        self.label_23 = QtGui.QLabel(self.gb_edit)
        self.label_23.setGeometry(QtCore.QRect(330, 190, 67, 17))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "الوظيفة :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.txt_edit_job = QtGui.QLineEdit(self.gb_edit)
        self.txt_edit_job.setGeometry(QtCore.QRect(20, 190, 271, 27))
        self.txt_edit_job.setObjectName(_fromUtf8("txt_edit_job"))
        self.label_24 = QtGui.QLabel(self.gb_edit)
        self.label_24.setGeometry(QtCore.QRect(330, 230, 67, 17))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "التليفون :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.txt_edit_tel = QtGui.QLineEdit(self.gb_edit)
        self.txt_edit_tel.setGeometry(QtCore.QRect(20, 230, 271, 27))
        self.txt_edit_tel.setObjectName(_fromUtf8("txt_edit_tel"))
        self.label_25 = QtGui.QLabel(self.gb_edit)
        self.label_25.setGeometry(QtCore.QRect(330, 270, 67, 17))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", " الايميل :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.txt_edit_email = QtGui.QLineEdit(self.gb_edit)
        self.txt_edit_email.setGeometry(QtCore.QRect(20, 270, 271, 27))
        self.txt_edit_email.setObjectName(_fromUtf8("txt_edit_email"))
        self.label_edit_msg = QtGui.QLabel(self.gb_edit)
        self.label_edit_msg.setGeometry(QtCore.QRect(20, 450, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_edit_msg.setFont(font)
        self.label_edit_msg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_edit_msg.setAutoFillBackground(False)
        self.label_edit_msg.setStyleSheet(_fromUtf8("color: rgb(255, 0, 4);"))
        self.label_edit_msg.setText(_fromUtf8(""))
        self.label_edit_msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_edit_msg.setObjectName(_fromUtf8("label_edit_msg"))
        self.bt_edit_delete = QtGui.QPushButton(self.gb_edit)
        self.bt_edit_delete.setGeometry(QtCore.QRect(20, 30, 91, 27))
        self.bt_edit_delete.setText(QtGui.QApplication.translate("MainWindow", "مسح اللاعب", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_edit_delete.setObjectName(_fromUtf8("bt_edit_delete"))
        self.bt_edit_canceledit = QtGui.QPushButton(self.gb_edit)
        self.bt_edit_canceledit.setGeometry(QtCore.QRect(20, 490, 97, 27))
        self.bt_edit_canceledit.setText(QtGui.QApplication.translate("MainWindow", "الغاء التعديل", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_edit_canceledit.setObjectName(_fromUtf8("bt_edit_canceledit"))
        self.label_22 = QtGui.QLabel(self.gb_edit)
        self.label_22.setGeometry(QtCore.QRect(330, 310, 67, 17))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "العنوان :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.txt_edit_address = QtGui.QPlainTextEdit(self.gb_edit)
        self.txt_edit_address.setGeometry(QtCore.QRect(20, 310, 271, 84))
        self.txt_edit_address.setObjectName(_fromUtf8("txt_edit_address"))
        self.bt_edit_edit_selected = QtGui.QPushButton(self.tab_4)
        self.bt_edit_edit_selected.setGeometry(QtCore.QRect(660, 470, 97, 27))
        self.bt_edit_edit_selected.setText(QtGui.QApplication.translate("MainWindow", "تعديل اللاعب", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_edit_edit_selected.setObjectName(_fromUtf8("bt_edit_edit_selected"))
        self.list_search = QtGui.QListWidget(self.tab_4)
        self.list_search.setGeometry(QtCore.QRect(580, 150, 331, 281))
        self.list_search.setObjectName(_fromUtf8("list_search"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(826, 120, 81, 20))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "نتيجة البحث :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(841, 20, 81, 20))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "اختار اللعبة :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.combo_expired = QtGui.QComboBox(self.tab_5)
        self.combo_expired.setGeometry(QtCore.QRect(555, 20, 271, 27))
        self.combo_expired.setObjectName(_fromUtf8("combo_expired"))
        self.combo_expired.addItem(_fromUtf8(""))
        self.combo_expired.setItemText(0, QtGui.QApplication.translate("MainWindow", "Aikido", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_expired.addItem(_fromUtf8(""))
        self.combo_expired.setItemText(1, QtGui.QApplication.translate("MainWindow", "KungFu", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_expired.addItem(_fromUtf8(""))
        self.combo_expired.setItemText(2, QtGui.QApplication.translate("MainWindow", "Free Style", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_expired.addItem(_fromUtf8(""))
        self.combo_expired.setItemText(3, QtGui.QApplication.translate("MainWindow", "Golden", None, QtGui.QApplication.UnicodeUTF8))
        self.list_expired = QtGui.QListWidget(self.tab_5)
        self.list_expired.setGeometry(QtCore.QRect(390, 120, 431, 391))
        self.list_expired.setObjectName(_fromUtf8("list_expired"))
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(716, 80, 201, 20))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "اللاعبين الذين  انتهت اشتراكاتهم :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(550, 10, 411, 541))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "معلومات اللاعب ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(330, 70, 67, 17))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "الاسم :", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(320, 110, 81, 20))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "تاريخ الميلاد :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(320, 150, 81, 20))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "النشاط :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(300, 350, 101, 20))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "تاريخ الانضمام  :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txt_add_name = QtGui.QLineEdit(self.groupBox)
        self.txt_add_name.setGeometry(QtCore.QRect(20, 70, 271, 27))
        self.txt_add_name.setObjectName(_fromUtf8("txt_add_name"))
        self.date_add_bd = QtGui.QDateEdit(self.groupBox)
        self.date_add_bd.setGeometry(QtCore.QRect(20, 110, 271, 27))
        self.date_add_bd.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "M/d/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_add_bd.setObjectName(_fromUtf8("date_add_bd"))
        self.combo_add_game = QtGui.QComboBox(self.groupBox)
        self.combo_add_game.setGeometry(QtCore.QRect(20, 150, 271, 27))
        self.combo_add_game.setObjectName(_fromUtf8("combo_add_game"))
        self.combo_add_game.addItem(_fromUtf8(""))
        self.combo_add_game.setItemText(0, QtGui.QApplication.translate("MainWindow", "Aikido", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_add_game.addItem(_fromUtf8(""))
        self.combo_add_game.setItemText(1, QtGui.QApplication.translate("MainWindow", "KungFu", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_add_game.addItem(_fromUtf8(""))
        self.combo_add_game.setItemText(2, QtGui.QApplication.translate("MainWindow", "Free Style", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_add_game.addItem(_fromUtf8(""))
        self.combo_add_game.setItemText(3, QtGui.QApplication.translate("MainWindow", "Golden", None, QtGui.QApplication.UnicodeUTF8))
        self.date_add_joindate = QtGui.QDateEdit(self.groupBox)
        self.date_add_joindate.setGeometry(QtCore.QRect(20, 350, 271, 27))
        self.date_add_joindate.setDate(QtCore.QDate(2012, 1, 1))
        self.date_add_joindate.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "M/d/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_add_joindate.setObjectName(_fromUtf8("date_add_joindate"))
        self.bt_add = QtGui.QPushButton(self.groupBox)
        self.bt_add.setGeometry(QtCore.QRect(130, 420, 97, 27))
        self.bt_add.setText(QtGui.QApplication.translate("MainWindow", "اضافة", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_add.setObjectName(_fromUtf8("bt_add"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(330, 190, 67, 17))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "الوظيفة :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.txt_add_job = QtGui.QLineEdit(self.groupBox)
        self.txt_add_job.setGeometry(QtCore.QRect(20, 190, 271, 27))
        self.txt_add_job.setObjectName(_fromUtf8("txt_add_job"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(330, 230, 67, 17))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "التليفون :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.txt_add_tel = QtGui.QLineEdit(self.groupBox)
        self.txt_add_tel.setGeometry(QtCore.QRect(20, 230, 271, 27))
        self.txt_add_tel.setObjectName(_fromUtf8("txt_add_tel"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(330, 270, 67, 17))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", " الايميل :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.txt_add_email = QtGui.QLineEdit(self.groupBox)
        self.txt_add_email.setGeometry(QtCore.QRect(20, 270, 271, 27))
        self.txt_add_email.setObjectName(_fromUtf8("txt_add_email"))
        self.label_add_msg = QtGui.QLabel(self.groupBox)
        self.label_add_msg.setGeometry(QtCore.QRect(20, 390, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_add_msg.setFont(font)
        self.label_add_msg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_add_msg.setAutoFillBackground(False)
        self.label_add_msg.setStyleSheet(_fromUtf8("color: rgb(255, 0, 4);"))
        self.label_add_msg.setText(_fromUtf8(""))
        self.label_add_msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_add_msg.setObjectName(_fromUtf8("label_add_msg"))
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(330, 310, 67, 17))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "العنوان :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.txt_add_address = QtGui.QLineEdit(self.groupBox)
        self.txt_add_address.setGeometry(QtCore.QRect(20, 310, 271, 27))
        self.txt_add_address.setText(_fromUtf8(""))
        self.txt_add_address.setObjectName(_fromUtf8("txt_add_address"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 10, 591, 551))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "تجديد للاعب", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(460, 50, 121, 20))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "بحث عن اللاعب :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(496, 90, 81, 20))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "اسم اللاعب:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.txt_renew_name = QtGui.QLineEdit(self.groupBox_2)
        self.txt_renew_name.setGeometry(QtCore.QRect(230, 90, 261, 27))
        self.txt_renew_name.setObjectName(_fromUtf8("txt_renew_name"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(490, 360, 81, 20))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "تاريخ التجديد :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.date_renew_renewdate = QtGui.QDateEdit(self.groupBox_2)
        self.date_renew_renewdate.setGeometry(QtCore.QRect(250, 360, 211, 27))
        self.date_renew_renewdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2012, 2, 1), QtCore.QTime(0, 0, 0)))
        self.date_renew_renewdate.setDate(QtCore.QDate(2012, 2, 1))
        self.date_renew_renewdate.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7999, 12, 31), QtCore.QTime(23, 59, 59)))
        self.date_renew_renewdate.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "M/d/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_renew_renewdate.setCalendarPopup(True)
        self.date_renew_renewdate.setObjectName(_fromUtf8("date_renew_renewdate"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(486, 410, 81, 20))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "قيمة التجديد:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.txt_renew_renewvalue = QtGui.QLineEdit(self.groupBox_2)
        self.txt_renew_renewvalue.setGeometry(QtCore.QRect(350, 410, 113, 27))
        self.txt_renew_renewvalue.setObjectName(_fromUtf8("txt_renew_renewvalue"))
        self.bt_renew = QtGui.QPushButton(self.groupBox_2)
        self.bt_renew.setGeometry(QtCore.QRect(110, 410, 97, 27))
        self.bt_renew.setText(QtGui.QApplication.translate("MainWindow", "جدد", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_renew.setObjectName(_fromUtf8("bt_renew"))
        self.bt_renew_search = QtGui.QPushButton(self.groupBox_2)
        self.bt_renew_search.setGeometry(QtCore.QRect(100, 90, 97, 27))
        self.bt_renew_search.setText(QtGui.QApplication.translate("MainWindow", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_renew_search.setObjectName(_fromUtf8("bt_renew_search"))
        self.date_renew_validTill = QtGui.QDateEdit(self.groupBox_2)
        self.date_renew_validTill.setGeometry(QtCore.QRect(190, 450, 271, 27))
        self.date_renew_validTill.setDate(QtCore.QDate(2012, 1, 1))
        self.date_renew_validTill.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "M/d/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_renew_validTill.setObjectName(_fromUtf8("date_renew_validTill"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(470, 450, 101, 20))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "انتهاء اخر تجديد :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.list_renew = QtGui.QListWidget(self.groupBox_2)
        self.list_renew.setGeometry(QtCore.QRect(230, 130, 256, 192))
        self.list_renew.setObjectName(_fromUtf8("list_renew"))
        self.label_renew_msg = QtGui.QLabel(self.groupBox_2)
        self.label_renew_msg.setGeometry(QtCore.QRect(190, 490, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_renew_msg.setFont(font)
        self.label_renew_msg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_renew_msg.setAutoFillBackground(False)
        self.label_renew_msg.setStyleSheet(_fromUtf8("color: rgb(255, 0, 4);"))
        self.label_renew_msg.setText(_fromUtf8(""))
        self.label_renew_msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_renew_msg.setObjectName(_fromUtf8("label_renew_msg"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "الصفحة الرئيسية", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "بحث عن لاعب", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "عرض اللاعبين التي نفذت اشتراكاتهم", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "معلومات اللاعبين", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "اضافة لاعب جديد", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "تجديد للاعب", None, QtGui.QApplication.UnicodeUTF8))

